- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "mysql", state: "present" }
    - { name: "nginx", state: "present" }
    - { name: "zip", state: "present" }